sudo: required

language: generic

services:
  - docker

install:
  - curl -fsSL get.docksal.io | sh
  - fin version
  - fin sysinfo

before_script:
  - fin andock enable
  - fin andock connect "defalult" "YOUR-DOMAIN.com"

# Uncomment to build and deploy
#script:
# - fin andock build && fin andock deploy