version: "2.1"

services:
  # Web
  web:
    extends:
      file: ${HOME}/.docksal/stacks/services.yml
      service: web
    depends_on:
      - cli
  # Varnish
  varnish:
    extends:
      file: ${HOME}/.docksal/stacks/services.yml
      service: varnish
    depends_on:
      - web
  # DB
  db:
    extends:
      file: ${HOME}/.docksal/stacks/services.yml
      service: db

  # CLI
  cli:
    extends:
      file: ${HOME}/.docksal/stacks/services.yml
      service: cli

  # andock
  andock:
    hostname: andock
    image: ${ANDOCK_IMAGE:-andockio/andock:latest}
    volumes:
      - project_root:/var/www:rw,nocopy  # Project root volume
      - docksal_ssh_agent:/.ssh-agent:ro
    environment:
      - GIT_USER_EMAIL
      - GIT_USER_NAME
      - HOST_UID
      - HOST_GID

  # MailHog
  mail:
    extends:
      file: ${HOME}/.docksal/stacks/services.yml
      service: mail
